/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.SeeBill;

import dao.Order.OrderDAOImpl;
import java.util.List;
import model.DishModel;
import model.PartyModel;
import table.TableOrder;
import view.party.AddPartyMenuView;

/**
 *
 * @author Admin
 */
public class SeeBill extends javax.swing.JFrame {

    /**
     * Creates new form SeeBill
     */
    List<DishModel> gListOrder = null;
    public SeeBill() {
        initComponents();
    }
    
public SeeBill(PartyModel _partyModel){
        initComponents();
        
        setOrderTable(_partyModel);
        setDataSeeBill(_partyModel);
    }
    
    private void setOrderTable(PartyModel _partyModel){
        gListOrder = OrderDAOImpl.getInstance().getListByID(_partyModel.getID());
        TableOrder tb = new TableOrder();
        tb.setOrderDetailsToTable(gListOrder, _partyModel, tableOrder);
    }
    
    private void setDataSeeBill(PartyModel partyModel){
        this.setTitle("Xem hóa đơn");
        this.setLocationRelativeTo(null);
        JLB_Name.setText(partyModel.getCustomer().getName());
        JLB_PhoneNumber.setText(partyModel.getCustomer().getPhoneNumber());
        JLB_Gender.setText(partyModel.getCustomer().getSex() == 0 ? "Nữ" : "Nam");
        jlb_NameParty.setText(partyModel.getPartyName());
        jlb_NumberTable.setText(partyModel.getTableNumber() + "");
        jlb_Date.setText(partyModel.getDate()+"");
        jlb_Time.setText(partyModel.getTime()+"");
        jlb_Location.setText(partyModel.getLocation());
        JLB_CustomerID.setText("ID: " + partyModel.getCustomer().getID() + "");
        jlb_PartyID.setText("ID: " + partyModel.getID() + "");
        
        AddPartyMenuView addPartyMenuView = new AddPartyMenuView(partyModel);
        Double total = addPartyMenuView.getgTotalPricePerTable()*partyModel.getTableNumber();
        jlb_Total.setText(total + "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jpnTitle = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jpnBody = new javax.swing.JPanel();
        jpnTop = new javax.swing.JPanel();
        jpn_Customer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JLB_CustomerID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JLB_Name = new javax.swing.JLabel();
        JLB_PhoneNumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JLB_Gender = new javax.swing.JLabel();
        jpn_Party = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlb_PartyID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlb_NameParty = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlb_NumberTable = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlb_Date = new javax.swing.JLabel();
        jlb_Time = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlb_Location = new javax.swing.JLabel();
        jpnCenter = new javax.swing.JPanel();
        ScrollPaneTable = new javax.swing.JScrollPane();
        tableOrder = new view.component.table.Table();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlb_Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpnTitle.setBackground(new java.awt.Color(255, 255, 255));

        jlbTitle.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(0, 102, 102));
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("HÓA ĐƠN TIỆC LAN HUỆ");

        javax.swing.GroupLayout jpnTitleLayout = new javax.swing.GroupLayout(jpnTitle);
        jpnTitle.setLayout(jpnTitleLayout);
        jpnTitleLayout.setHorizontalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpnTitleLayout.setVerticalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTitleLayout.createSequentialGroup()
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnBody.setBackground(new java.awt.Color(255, 255, 255));

        jpnTop.setBackground(new java.awt.Color(255, 255, 255));
        jpnTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpn_Customer.setBackground(new java.awt.Color(255, 255, 255));
        jpn_Customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Thông tin khách hàng:");
        jpn_Customer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 50));

        JLB_CustomerID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLB_CustomerID.setText("ID:");
        jpn_Customer.add(JLB_CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 130, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Tên:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Customer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("SĐT:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Customer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 30));

        JLB_Name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JLB_Name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Customer.add(JLB_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 230, 30));

        JLB_PhoneNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JLB_PhoneNumber.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Customer.add(JLB_PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Giới tính:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Customer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 68, 30));

        JLB_Gender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JLB_Gender.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Customer.add(JLB_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 60, 30));

        jpnTop.add(jpn_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        jpn_Party.setBackground(new java.awt.Color(255, 255, 255));
        jpn_Party.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Thông tin tiệc:");
        jpn_Party.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 0, 300, 50));

        jlb_PartyID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlb_PartyID.setText("ID:");
        jpn_Party.add(jlb_PartyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 130, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Tên tiệc:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 30));

        jlb_NameParty.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlb_NameParty.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jlb_NameParty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 280, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Số bàn:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 30));

        jlb_NumberTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlb_NumberTable.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jlb_NumberTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 280, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Thời gian:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 30));

        jlb_Date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlb_Date.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jlb_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 30));

        jlb_Time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlb_Time.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jlb_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 160, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Địa điểm:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 30));

        jlb_Location.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlb_Location.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpn_Party.add(jlb_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 530, 52));

        jpnTop.add(jpn_Party, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 660, -1));

        jpnCenter.setBackground(new java.awt.Color(255, 255, 255));
        jpnCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên món", "Giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableOrder.setShowGrid(true);
        tableOrder.getTableHeader().setReorderingAllowed(false);
        ScrollPaneTable.setViewportView(tableOrder);

        jpnCenter.add(ScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 600, 130));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Thông tin món:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpnCenter.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 453, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Tổng tiền thanh toán:");
        jpnCenter.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 195, 70));

        jlb_Total.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jpnCenter.add(jlb_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 120, 70));

        javax.swing.GroupLayout jpnBodyLayout = new javax.swing.GroupLayout(jpnBody);
        jpnBody.setLayout(jpnBodyLayout);
        jpnBodyLayout.setHorizontalGroup(
            jpnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBodyLayout.createSequentialGroup()
                .addGroup(jpnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnBodyLayout.setVerticalGroup(
            jpnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBodyLayout.createSequentialGroup()
                .addComponent(jpnTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpnCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeeBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLB_CustomerID;
    private javax.swing.JLabel JLB_Gender;
    private javax.swing.JLabel JLB_Name;
    private javax.swing.JLabel JLB_PhoneNumber;
    private javax.swing.JScrollPane ScrollPaneTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlb_Date;
    private javax.swing.JLabel jlb_Location;
    private javax.swing.JLabel jlb_NameParty;
    private javax.swing.JLabel jlb_NumberTable;
    private javax.swing.JLabel jlb_PartyID;
    private javax.swing.JLabel jlb_Time;
    private javax.swing.JLabel jlb_Total;
    private javax.swing.JPanel jpnBody;
    private javax.swing.JPanel jpnCenter;
    private javax.swing.JPanel jpnTitle;
    private javax.swing.JPanel jpnTop;
    private javax.swing.JPanel jpn_Customer;
    private javax.swing.JPanel jpn_Party;
    private view.component.table.Table tableOrder;
    // End of variables declaration//GEN-END:variables
}
