/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.staff;

import java.util.List;
import javax.swing.JScrollBar;
import model.RoleModel;
import model.StaffModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import service.role.RoleServiceImpl;
import view.component.scroll.ScrollBarCus;

/**
 *
 * @author Admin
 */
public class addStaff extends javax.swing.JFrame {

    StaffModel staffModel = null;
    List<RoleModel> gListRole = null ;
    RoleModel gRoleModel = null;
    public addStaff() {
        initComponents();
        
        // set vertical and horizontal scroll bar
        ScrollBarCus sb = new ScrollBarCus();
        sb.setOrientation(JScrollBar.HORIZONTAL);
        
        gListRole = new RoleServiceImpl().getList();
        setComboboxRole();
        
        editBtn2.setVisible(false);
    }
    
    public addStaff(StaffModel _staffModel){
        initComponents();
        // set vertical and horizontal scroll bar
        ScrollBarCus sb = new ScrollBarCus();
        System.out.println("11111");
        sb.setOrientation(JScrollBar.HORIZONTAL);
        
        setData(_staffModel);
        setReadOnly();
        // set button
        saveBtn2.setVisible(false);
        editBtn2.setVisible(true);
    }
    
    private void setData(StaffModel _staffModel){
        this.setTitle("Xem Nhân Viên");
        TF_staffID.setText(_staffModel.getStaffID()+ "");
        comboBoxRole.addItem(_staffModel.getRole());
        comboBoxStaff.addItem(_staffModel.getName());
        TF_phoneNumber.setText(_staffModel.getSdt());
        TF_CCCD.setText(_staffModel.getCccd());
        panelLocation2.setAddress(_staffModel.getAddress());
    }
    
    private void setReadOnly(){
        comboBoxRole.setEditable(false);
        comboBoxStaff.setEditable(false);
        TF_phoneNumber.setEditable(false);
        TF_CCCD.setEditable(false);
    }
    
    private void setComboboxRole(){
        comboBoxRole.removeAllItems();
        for(int i=0; i<gListRole.size(); i++){
            comboBoxRole.addItem(gListRole.get(i).getRoleName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLocation2 = new view.component.PanelLocation();
        panelStaff = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxStaff = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        TF_phoneNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_phoneNumber1 = new javax.swing.JTextField();
        TF_CCCD = new javax.swing.JTextField();
        bottom2 = new javax.swing.JPanel();
        saveBtn2 = new rojeru_san.complementos.RSButtonHover();
        editBtn2 = new rojeru_san.complementos.RSButtonHover();
        cancelBtn2 = new rojeru_san.complementos.RSButtonHover();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_staffID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboBoxRole = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLocation2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        jPanel1.add(panelLocation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 243, 596, 149));

        panelStaff.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        panelStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nhân viên (*)");
        panelStaff.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 298, 22));

        comboBoxStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStaffActionPerformed(evt);
            }
        });
        panelStaff.add(comboBoxStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 10, 298, -1));

        jLabel6.setText("SĐT liên hệ (*)");
        panelStaff.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 298, 22));

        TF_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_phoneNumberActionPerformed(evt);
            }
        });
        panelStaff.add(TF_phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 42, 298, -1));

        jLabel3.setText("Căn cước công dân (CMND) (*):");
        panelStaff.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, -1));

        TF_phoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_phoneNumber1ActionPerformed(evt);
            }
        });
        panelStaff.add(TF_phoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 42, 298, -1));
        panelStaff.add(TF_CCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 74, 297, -1));

        jPanel1.add(panelStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 107, -1, -1));

        bottom2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        saveBtn2.setBackground(new java.awt.Color(10, 77, 104));
        saveBtn2.setText("Lưu");
        saveBtn2.setColorHover(new java.awt.Color(14, 112, 152));
        saveBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBtn2.setPreferredSize(new java.awt.Dimension(110, 40));
        saveBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn2ActionPerformed(evt);
            }
        });
        bottom2.add(saveBtn2);

        editBtn2.setBackground(new java.awt.Color(10, 77, 104));
        editBtn2.setText("Chỉnh sửa");
        editBtn2.setColorHover(new java.awt.Color(14, 112, 152));
        editBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editBtn2.setPreferredSize(new java.awt.Dimension(110, 40));
        editBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn2ActionPerformed(evt);
            }
        });
        bottom2.add(editBtn2);

        cancelBtn2.setBackground(new java.awt.Color(10, 77, 104));
        cancelBtn2.setText("Hủy");
        cancelBtn2.setColorHover(new java.awt.Color(14, 112, 152));
        cancelBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelBtn2.setPreferredSize(new java.awt.Dimension(110, 40));
        cancelBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtn2MouseClicked(evt);
            }
        });
        cancelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn2ActionPerformed(evt);
            }
        });
        bottom2.add(cancelBtn2);

        jPanel1.add(bottom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 502, 596, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID (*)");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 52, 28));
        jPanel2.add(TF_staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 15, 181, -1));

        jLabel2.setText("Chức vụ (*)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 18, 72, -1));

        comboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRoleActionPerformed(evt);
            }
        });
        jPanel2.add(comboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 15, 215, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 24, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtn2ActionPerformed

    private void cancelBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtn2MouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBtn2MouseClicked

    private void editBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtn2ActionPerformed

    private void saveBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn2ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_saveBtn2ActionPerformed

    private void TF_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_phoneNumberActionPerformed

    private void comboBoxStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStaffActionPerformed
//        if (gListCustomer != null) {
//            gCustomerModel = gListCustomer.get(comboBoxStaff.getSelectedIndex());
//            TF_phoneNumber.setText(gCustomerModel.getPhoneNumber());
//        }
    }//GEN-LAST:event_comboBoxStaffActionPerformed

    private void TF_phoneNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_phoneNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_phoneNumber1ActionPerformed

    private void comboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRoleActionPerformed
        if(gListRole != null){
            gRoleModel = gListRole.get(comboBoxRole.getSelectedIndex());
        }
    }//GEN-LAST:event_comboBoxRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_CCCD;
    private javax.swing.JTextField TF_phoneNumber;
    private javax.swing.JTextField TF_phoneNumber1;
    private javax.swing.JTextField TF_staffID;
    private javax.swing.JPanel bottom2;
    private rojeru_san.complementos.RSButtonHover cancelBtn2;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JComboBox<String> comboBoxStaff;
    private rojeru_san.complementos.RSButtonHover editBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private view.component.PanelLocation panelLocation2;
    private javax.swing.JPanel panelStaff;
    private rojeru_san.complementos.RSButtonHover saveBtn2;
    // End of variables declaration//GEN-END:variables
}
