package view.main;

import dao.Customer.CustomerDAOImpl;
import dao.Invoice.InvoiceDAOImpl;
import dao.Party.PartyDAOImpl;
import dao.Staff.StaffDAOImpl;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import java.util.Map;
import model.CustomerModel;
import model.HappenStatusModel;
import model.PartyModel;
import model.PaymentStatusModel;
import model.StaffModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

public class DashBoardView extends javax.swing.JPanel {

    List<StaffModel> gListStaff = StaffDAOImpl.getInstance().getList();
    List<CustomerModel> gListCustomer = CustomerDAOImpl.getInstance().getList();
    List<PartyModel> gListParty = PartyDAOImpl.getInstance().getList();

    public DashBoardView() {
        initComponents();
        setCountPartyComingSoon();
        setCountPartyNotPaymentAndDone();
        setCountCustomer();
        setCountStaff();
        showBarChart();
    }

    private void setCountPartyComingSoon() {
        int count = 0;
        for (int i = 0; i < gListParty.size(); i++) {
            if (HappenStatusModel.COMING_SOON == gListParty.get(i).getHappenStatus().getStatusCode()) {
                count++;
            }
        }
        countPartyComingSoon.setText(count + "");

    }

    private void setCountPartyNotPaymentAndDone() {
        int count = 0;
        for (int i = 0; i < gListParty.size(); i++) {
            if (PaymentStatusModel.UN_PAID == gListParty.get(i).getPaymentStatus().getStatusCode() && gListParty.get(i).getHappenStatus().getStatusCode() == HappenStatusModel.DONE) {
                count++;
            }
        }
        countPartyNotPayment.setText(count + "");
    }

    private void setCountCustomer() {
        int count = 0;
        count = gListCustomer.size();
        countCustomer.setText(count + "");
    }

    private void setCountStaff() {
        int count = 0;
        count = gListStaff.size();
        countStaff.setText(count + "");
    }

    private static CategoryDataset createDataset() {
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        Map<Integer, Double> mapData = InvoiceDAOImpl.getInstance().getRevenueByMonthAtNowYear();

        for (int i = 1; i <= 12; i++) {
            dataset.addValue(mapData.get(i), "Doanh thu", "Tháng " + i);
        }

        return dataset;
    }

    private void showBarChart() {
        JFreeChart barChart = ChartFactory.createBarChart(
                "DOANH THU THEO THÁNG TRONG NĂM 2023",
                "", "Doanh thu (Đồng)",
                createDataset(), PlotOrientation.VERTICAL, false, true, false);
        barChart.setBackgroundPaint(new Color(249, 245, 231));

        CategoryPlot categoryPlot = barChart.getCategoryPlot();
        categoryPlot.setRangeGridlinePaint(Color.black);
        Font font = new Font("Segoe UI", Font.BOLD, 16);
        categoryPlot.getDomainAxis().setLabelFont(font);
        categoryPlot.getRangeAxis().setLabelFont(font);

        BarRenderer rendered = (BarRenderer) categoryPlot.getRenderer();
        rendered.setSeriesPaint(0, new Color(148, 175, 159));
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(barChartPanel.getSize());

        barChartPanel.setLayout(new GridLayout(1, 1));
        barChartPanel.add(chartPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        countPartyComingSoon = new view.component.LabelGoogleIcon();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        countPartyNotPayment = new view.component.LabelGoogleIcon();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        countCustomer = new view.component.LabelGoogleIcon();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        countStaff = new view.component.LabelGoogleIcon();
        barChartPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1017, 576));

        jpnRoot.setBackground(new java.awt.Color(249, 245, 231));
        jpnRoot.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jpnRoot.setForeground(new java.awt.Color(255, 255, 255));
        jpnRoot.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jpnRoot.setPreferredSize(new java.awt.Dimension(1017, 576));
        jpnRoot.setLayout(new java.awt.BorderLayout(0, 20));

        jPanel5.setBackground(jpnRoot.getBackground());
        jPanel5.setMinimumSize(new java.awt.Dimension(776, 140));
        jPanel5.setLayout(new java.awt.GridLayout(1, 4, 20, 10));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel1.setToolTipText("Số lượng tiệc sắp tới");
        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(10);
        jPanel1.setLayout(verticalLayout1);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Số lượng tiệc sắp tới");
        jPanel1.add(jLabel1);

        countPartyComingSoon.setForeground(new java.awt.Color(255, 255, 255));
        countPartyComingSoon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countPartyComingSoon.setText("10");
        countPartyComingSoon.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        countPartyComingSoon.setIconColor(new java.awt.Color(255, 255, 255));
        countPartyComingSoon.setIconSize(50.0F);
        jPanel1.add(countPartyComingSoon);

        jPanel5.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel2.setToolTipText("Số lượng tiệc đã xong + chưa thanh toán");
        org.jdesktop.swingx.VerticalLayout verticalLayout2 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout2.setGap(10);
        jPanel2.setLayout(verticalLayout2);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(jLabel1.getForeground());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số lượng tiệc đã xong + chưa thanh toán");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2);

        countPartyNotPayment.setForeground(new java.awt.Color(255, 255, 255));
        countPartyNotPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countPartyNotPayment.setText("4");
        countPartyNotPayment.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        countPartyNotPayment.setIconColor(new java.awt.Color(255, 255, 255));
        countPartyNotPayment.setIconSize(50.0F);
        jPanel2.add(countPartyNotPayment);

        jPanel5.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(10, 77, 104)));
        jPanel3.setToolTipText("Số lượng khách hàng");
        org.jdesktop.swingx.VerticalLayout verticalLayout3 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout3.setGap(10);
        jPanel3.setLayout(verticalLayout3);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(jLabel1.getForeground());
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số lượng khách hàng");
        jPanel3.add(jLabel3);

        countCustomer.setForeground(new java.awt.Color(255, 255, 255));
        countCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countCustomer.setText("25");
        countCustomer.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        countCustomer.setIconColor(new java.awt.Color(255, 255, 255));
        countCustomer.setIconSize(50.0F);
        jPanel3.add(countCustomer);

        jPanel5.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(10, 77, 104)));
        jPanel4.setToolTipText("Số lượng nhân viên");
        org.jdesktop.swingx.VerticalLayout verticalLayout4 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout4.setGap(10);
        jPanel4.setLayout(verticalLayout4);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(jLabel1.getForeground());
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Số lượng nhân viên");
        jPanel4.add(jLabel4);

        countStaff.setForeground(new java.awt.Color(255, 255, 255));
        countStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countStaff.setText("100");
        countStaff.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        countStaff.setIconColor(new java.awt.Color(255, 255, 255));
        countStaff.setIconSize(50.0F);
        jPanel4.add(countStaff);

        jPanel5.add(jPanel4);

        jpnRoot.add(jPanel5, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout barChartPanelLayout = new javax.swing.GroupLayout(barChartPanel);
        barChartPanel.setLayout(barChartPanelLayout);
        barChartPanelLayout.setHorizontalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );
        barChartPanelLayout.setVerticalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jpnRoot.add(barChartPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barChartPanel;
    private view.component.LabelGoogleIcon countCustomer;
    private view.component.LabelGoogleIcon countPartyComingSoon;
    private view.component.LabelGoogleIcon countPartyNotPayment;
    private view.component.LabelGoogleIcon countStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jpnRoot;
    // End of variables declaration//GEN-END:variables
}
